apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-seller
  labels:
    app: frontend-seller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-seller
  template:
    metadata:
      labels:
        app: frontend-seller
    spec:
      containers:
        - name: frontend-seller
          image: midso/frontend-seller
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"          
            - name: NUXT_SERVICE_SELLER_BASE
              value: http://service-seller.default.svc.cluster.local:8000
            - name: NUXT_SERVICE_PRODUCT_BASE
              value: http://service-product.default.svc.cluster.local:8001
            - name: NUXT_SERVICE_LLM_BASE
              value: http://service-llm.default.svc.cluster.local:8002
            - name: NUXT_SERVICE_MEDIA_BASE
              value: http://service-media.default.svc.cluster.local:8003
            - name: NUXT_SERVICE_GATEWAY_BASE
              value: http://service-gateway.default.svc.cluster.local:8006
            - name: NUXT_SERVICE_NOTIFICATION_BASE
              value: http://service-notification.default.svc.cluster.local:8009  
            - name: NUXT_SERVICE_CHAT_BASE
              value: http://service-chat.default.svc.cluster.local:8010  
            - name: NUXT_REDIS_CHAT_BASE
              value: redis://redis-chat.default.svc.cluster.local:6379                                             
            - name: NUXT_PUBLIC_MEDIA_CDN
              value: "/api/media"
            - name: NUXT_PUBLIC_CARDANO_NETWORK
              value: "mainnet"   
            - name: NUXT_PUBLIC_MIDSO_BASE
              value: "midso.io"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-seller
spec:
  selector:
    app: frontend-seller
  ports:
    - protocol: TCP
      port: 81
      targetPort: 3000
  type: ClusterIP
