apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-gateway-consumer
spec:
  selector:
    matchLabels:
      role: service-gateway-consumer
  replicas: 1
  template:
    metadata:
      labels:
        role: service-gateway-consumer
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: service-gateway-consumer
          image: midso/base-consumer
          ports:
            - containerPort: 3000                   
          env:
            - name: NODE_ENV
              value: "production"     
            - name: SERVICE_NAME
              value: service-gateway   
            - name: CONSUMER_GROUP
              value: service-gateway-group   
            - name: DURABLE_NAME
              value: service-gateway-consumer                           
            - name: STREAM_LIST
              value: service-seller,service-product
            - name: FILTER_SUBJECTS
              value: "service-product.CreateProduct,service-product.UpdateProduct,service-product.DeleteProduct,service-seller.CreateSeller,service-seller.UpdateSeller"              
            - name : HANDLER_REDIS_BOOKS_HOST
              value: redis://redis-books:6379               
            - name: DATABASE_NAME
              value: service_gateway       
            - name: DATABASE_USER
              value: marketplace                  
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DATABASE_HOST  
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: master  
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: port                                     
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password-secret
                  key: password   
            - name: NATS_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: nats-cluster-config
                  key: hosts 
                  

          resources:
            requests:
              cpu: "10m"
              memory: "100Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"   

     
