apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-product-consumer
spec:
  selector:
    matchLabels:
      role: service-product-consumer
  replicas: 1
  template:
    metadata:
      labels:
        role: service-product-consumer
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: service-product-consumer
          image: midso/base-consumer
          ports:
            - containerPort: 3000
          env:       
            - name: NODE_ENV
              value: "production"
            - name: SERVICE_NAME
              value: service-product
            - name: CONSUMER_GROUP
              value: service-product-group
            - name: DURABLE_NAME
              value: service-product-consumer
            - name: STREAM_LIST
              value: service-processor
            - name: FILTER_SUBJECTS
              value: "service-processor.ProcessedFile"    
            - name: DATABASE_NAME
              value: service_product
            - name: DATABASE_USER
              value: marketplace                                
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: master
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: port
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password-secret
                  key: password 
            - name: NATS_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: nats-cluster-config
                  key: hosts 

          resources:
            requests:
              cpu: "10m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"   
