apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-query
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-query
  template:
    metadata:
      labels:
        role: service-query
    spec:
      containers:
        - name: service-query
          image: midso/service-query
          env:
            - name: NODE_ENV
              value: "production"                                                                          
            - name: DATABASE_NAME
              value: service_query       
            - name: DATABASE_USER
              value: marketplace     
            - name : REDIS_RATELIMIT_HOST
              value: "redis://redis-limiter:6379"
            - name : REDIS_PRICE_HOST
              value: "redis://redis-price:6379"   
            - name : REDIS_FEED_HOST
              value: "redis://redis-feed:6379" 
            - name : REDIS_BOOKS_HOST
              value: "redis://redis-books:6379"                               
            - name: DATABASE_HOST  
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: master  
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: port                                     
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password-secret
                  key: password                
            - name: AGENT_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: agent-key-secret
                  key: key 
            - name: WEAVIATE_HOST
              valueFrom:
                configMapKeyRef:
                  name: weaviate-cluster-config
                  key: host 
            - name: EMBEDDING_HOST
              valueFrom:
                configMapKeyRef:
                  name: embedding-config
                  key: host              


          resources:
            requests:
              cpu: "10m"
              memory: "10Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"   
---

apiVersion: v1
kind: Service
metadata:
  name: service-query
spec:
  selector:
    role: service-query
  ports:
    - name: service-query
      protocol: TCP
      port: 8004
      targetPort: 8004
