apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-gateway-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-gateway-publisher
  template:
    metadata:
      labels:
        role: service-gateway-publisher
    spec:
      containers:
        - name: service-gateway-publisher
          image: midso/base-publisher
          env:                                                             
            - name: DATABASE_NAME
              value: service_gateway 
            - name: DATABASE_USER
              value: marketplace                                                                                                                                                              
            - name: STREAM_NAME
              value: service-gateway
            - name: STREAM_SUBJECT
              value: service-gateway.*              
            - name: QUERY_INTERVAL
              value: "10000"    
            - name: QUERY_LIMIT
              value: "100"  
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name                                                                
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: port                            
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password-secret
                  key: password      
            - name: DATABASE_HOST  
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: master  
            - name: NATS_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: nats-cluster-config
                  key: hosts 
                  
          resources:
            requests:
              cpu: "10m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"      
