apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-email
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-email
  template:
    metadata:
      labels:
        role: service-email
    spec:
      containers:
        - name: service-email
          image: midso/service-email
          env:
            - name: NODE_ENV
              value: "development"  
            - name: DATABASE_NAME
              value: service_email      
            - name: DATABASE_USER
              value: marketplace   
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name                                                                                                                         
            - name: DATABASE_HOST  
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: master  
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: port                                     
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password-secret
                  key: password   

          resources:
            requests:
              cpu: "10m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"    
---
apiVersion: v1
kind: Service
metadata:
  name: service-email
spec:
  selector:
    role: service-email
  ports:
    - name: service-email
      protocol: TCP
      port: 8000
      targetPort: 8000
