apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-processor-consumer
spec:
  selector:
    matchLabels:
      role: service-processor-consumer
  replicas: 1
  template:
    metadata:
      labels:
        role: service-processor-consumer
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: service-processor-consumer
          image: midso/base-consumer
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
            - name: SERVICE_NAME
              value: service-processor
            - name: CONSUMER_GROUP
              value: service-processor-group
            - name: DURABLE_NAME
              value: service-processor-consumer
            - name: STREAM_LIST
              value: service-media
            - name: FILTER_SUBJECTS
              value: "service-media.CreateFile"
            - name: DATABASE_NAME
              value: service_processor
            - name: DATABASE_USER
              value: marketplace
            - name: HANDLER_REDIS_HOST
              value: redis-processor.default.svc.cluster.local
            - name: HANDLER_MINIO_BUCKET
              value: media
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: master
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: port
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password-secret
                  key: password
            - name: NATS_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: nats-cluster-config
                  key: hosts 

          resources:
            requests:
              cpu: "10m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"   