apiVersion: v1
kind: Service
metadata:
  name: redis-chat
  namespace: default
  labels:
    app: redis-chat
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-chat

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-chat
  namespace: default
spec:
  serviceName: "redis-chat"
  replicas: 1
  selector:
    matchLabels:
      app: redis-chat
  template:
    metadata:
      labels:
        app: redis-chat
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-chat-data
              mountPath: /data
          command: [ "redis-server", "--appendonly", "yes" ]
  volumeClaimTemplates:
    - metadata:
        name: redis-chat-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 250Mi
