name: frontend-main

on:
  push:
    branches:
      - main
    paths:
      - 'frontend-main/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.MARKETPLACE_DOCKER_USER }}
          password: ${{ secrets.MARKETPLACE_DOCKER_PASSWORD }}

      - name: Build Docker image with CDN variable
        run: |
          docker build \
            --build-arg NUXT_PUBLIC_MEDIA_CDN=${{ secrets.NUXT_PUBLIC_MEDIA_CDN }} \
            -t midso/frontend-main ./frontend-main

      - name: Push Docker image
        run: docker push midso/frontend-main

      - name: Set up DigitalOcean CLI
        uses: digitalocean/action-doctl@v2.3.0
        with:
          token: ${{ secrets.MARKETPLACE_CLOUD_API }}

      - name: Set up kubeconfig
        run: doctl kubernetes cluster kubeconfig save midso

      - name: Restart Kubernetes deployment
        run: kubectl rollout restart deployment frontend-main
